{
 "title": "Winnovation dashboard",
 "tags": [
  "Linux",
  "Kubernetes",
  "Prophet",
  "Scaling Service",
  "Winnovation"
 ],
 "time": { "from": "now-1d", "to": "now+1h" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current and predicted Node Index",
   "type": "timeseries",
   "description": "Past prediction made by the prophet prediction model",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"Node Index\", createdat FROM past_prediction WHERE $__timeFilter(createdat)"
    },
    {
     "rawSql": "SELECT avg_usage_cpu * total_cpu / 100 AS \"Node Index\", \"time\" as time FROM metrics"
    }
   ]
  },
  {
   "title": "Mean absolute percentage error",
   "type": "timeseries",
   "description": "Describes the accuracy of the prediction model. ",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT error AS \"MAPE\", createdat \"Time\" FROM past_prediction_row WHERE $__timeFilter(createdat) ORDER BY createdat"
    }
   ]
  },
  {
   "title": "Total amount of active nodes",
   "type": "timeseries",
   "description": "Amount of active node (excluding Main & K11 tester)",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "description": "Describes the average CPU usage of the last two minutes. Excludes main node and k11 tester",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "(100 - (avg by (job) (rate(node_cpu_seconds_total{mode=\"idle\", node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"}[2m])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average requests per minute",
   "type": "timeseries",
   "description": "Requests per minute",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginx_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU cores",
     "type": "stat",
     "description": "Displays the total amount of CPU cores",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"}) by (cpu, instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU usage",
     "type": "gauge",
     "description": "Describes the average CPU usage of the last two minutes",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(100 - (avg by (job) (rate(node_cpu_seconds_total{mode=\"idle\", node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"}[2m])) * 100))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU usage MAIN",
     "type": "timeseries",
     "description": "Describes the average CPU usage of the last two minutes only main node",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "(100 - (avg by (job) (rate(node_cpu_seconds_total{mode=\"idle\", node=\"main-cffa2530a4b9\"}[2m])) * 100))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM",
     "type": "gauge",
     "description": "Requests per minute",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginx_http_requests_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average requests per minute",
     "type": "timeseries",
     "description": "Requests per minute",
     "gridPos": { "h": 13, "w": 18, "x": 6, "y": 107 },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginx_http_requests_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active pods",
     "type": "stat",
     "description": "Amount of active pods",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace!=\"kube-system\", node!=\"k11-tester-2-3aabaf8a4428\", node!=\"main-cffa2530a4b9\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active pods",
     "type": "timeseries",
     "description": "Amount of active pods",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace!=\"kube-system\", node!=\"k11-tester-2-3aabaf8a4428\", node!=\"main-cffa2530a4b9\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node count",
     "type": "stat",
     "description": "Amount of active node (excluding Main & K11 tester)",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_node_info{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total amount of active nodes",
     "type": "timeseries",
     "description": "Amount of active node (excluding Main & K11 tester)",
     "gridPos": { "h": 13, "w": 18, "x": 6, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_node_info{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total memory",
     "type": "stat",
     "description": "Displays the total amount of memory in bytes",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average memory usage",
     "type": "timeseries",
     "description": "Describes the average memory usage of the last two minutes",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    node_memory_MemTotal_bytes{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"} - \n    (node_memory_MemFree_bytes{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"} + \n    node_memory_Cached_bytes{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"} + \n    node_memory_Buffers_bytes{node!=\"main-cffa2530a4b9\", node!=\"k11-tester-2-3aabaf8a4428\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}